name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VM
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          REMOTE_HOST: ${{ secrets.HOST }}  
          REMOTE_USER: ${{ secrets.USERNAME }}  
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}  
          SCRIPT_BEFORE: | 
            git clone https://github.com/suryaanshrai/sayhello.git
            pip install -r requirements.txt
            sudo kill `sudo lsof -t -i :80` 
            sudo python3 manage.py runserver 80 > logs&

      - name: Notify on failure
        uses: actions/github-script@v6
        if: failure()
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Deployment failed!"
            })
